### ISSUE TITLE
Build of vsgPoints failes on macOS due to missing header file

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/vsgPoints#10]
My build sequence:

rm -rf vsgPoints
git clone https://github.com/vsg-dev/vsgPoints.git
cd vsgPoints
cmake  .
make

The code references a missing header, so the build fails:

[ 10%] Building CXX object src/vsgPoints/CMakeFiles/vsgPoints.dir/AsciiPoints.cpp.o
[ 20%] Building CXX object src/vsgPoints/CMakeFiles/vsgPoints.dir/BIN.cpp.o
[ 30%] Building CXX object src/vsgPoints/CMakeFiles/vsgPoints.dir/Brick.cpp.o
[ 40%] Building CXX object src/vsgPoints/CMakeFiles/vsgPoints.dir/Bricks.cpp.o
[ 50%] Building CXX object src/vsgPoints/CMakeFiles/vsgPoints.dir/BrickShaderSet.cpp.o
/Users/rainerge/Soft/Entwicklung/VSG3/vsgPoints/src/vsgPoints/BrickShaderSet.cpp:13:10: fatal error: 'vsgPoints/BrickBuilder.h' file not found
#include <vsgPoints/BrickBuilder.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by vsg-dev** [comment]
Sorry about that.  I refactored vsgPoiunts to clean it up but didn't spot this include error as I had installed vsgPoints and my build was picking up on an installed but now deleted header.

I have fixed this in the commit:  2e65c74181d0ed5be0de99d774c1e8823bfcf478
