### ISSUE TITLE
mesh disappears when rotated to the back

### ISSUE THREAD

**Issue by BH2WFR** [vsg-dev/vsgPoints#29]
VSG version: vsg 1.1.8 compiled by vcpkg
OS: Windows 11 24H2
Graphic Card: NVidia RTX 3050

Screen Record GIF (two samples):
![vsgPoints-mesh](https://github.com/user-attachments/assets/42f6ded1-2594-4706-97b9-c25188367b6f)

**Comment by robertosfield** [comment]
THis is standard back face culling that is enable for these particular datasets.  Please look up back face culling, it's standard feature of computer graphics for many decades.
